// <auto-generated />
namespace Gravenger.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateManyVarCharTypeColumnsToBeRequireOrHaveMaxLengthIfAppropriate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateManyVarCharTypeColumnsToBeRequireOrHaveMaxLengthIfAppropriate));
        
        string IMigrationMetadata.Id
        {
            get { return "201805281943100_UpdateManyVarCharTypeColumnsToBeRequireOrHaveMaxLengthIfAppropriate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
